const countries = [
    // África (54 países)
    { name: "África do Sul", continent: "África", capital: "Pretória", code: "ZA" },
    { name: "Angola", continent: "África", capital: "Luanda", code: "AO" },
    { name: "Argélia", continent: "África", capital: "Argel", code: "DZ" },
    { name: "Benim", continent: "África", capital: "Porto-Novo", code: "BJ" },
    { name: "Botsuana", continent: "África", capital: "Gaborone", code: "BW" },
    { name: "Burkina Faso", continent: "África", capital: "Ouagadougou", code: "BF" },
    { name: "Burundi", continent: "África", capital: "Gitega", code: "BI" },
    { name: "Cabo Verde", continent: "África", capital: "Praia", code: "CV" },
    { name: "Camarões", continent: "África", capital: "Yaoundé", code: "CM" },
    { name: "Chade", continent: "África", capital: "N'Djamena", code: "TD" },
    { name: "Comores", continent: "África", capital: "Moroni", code: "KM" },
    { name: "Congo", continent: "África", capital: "Brazzaville", code: "CG" },
    { name: "Costa do Marfim", continent: "África", capital: "Yamoussoukro", code: "CI" },
    { name: "Djibouti", continent: "África", capital: "Djibouti", code: "DJ" },
    { name: "Egito", continent: "África", capital: "Cairo", code: "EG" },
    { name: "Eritreia", continent: "África", capital: "Asmara", code: "ER" },
    { name: "Eswatini", continent: "África", capital: "Mbabane", code: "SZ" },
    { name: "Etiópia", continent: "África", capital: "Adis Abeba", code: "ET" },
    { name: "Gabão", continent: "África", capital: "Libreville", code: "GA" },
    { name: "Gâmbia", continent: "África", capital: "Banjul", code: "GM" },
    { name: "Gana", continent: "África", capital: "Acra", code: "GH" },
    { name: "Guiné", continent: "África", capital: "Conacri", code: "GN" },
    { name: "Guiné-Bissau", continent: "África", capital: "Bissau", code: "GW" },
    { name: "Guiné Equatorial", continent: "África", capital: "Malabo", code: "GQ" },
    { name: "Lesoto", continent: "África", capital: "Maseru", code: "LS" },
    { name: "Libéria", continent: "África", capital: "Monróvia", code: "LR" },
    { name: "Líbia", continent: "África", capital: "Trípoli", code: "LY" },
    { name: "Madagáscar", continent: "África", capital: "Antananarivo", code: "MG" },
    { name: "Malawi", continent: "África", capital: "Lilongwe", code: "MW" },
    { name: "Mali", continent: "África", capital: "Bamako", code: "ML" },
    { name: "Marrocos", continent: "África", capital: "Rabat", code: "MA" },
    { name: "Maurício", continent: "África", capital: "Port Louis", code: "MU" },
    { name: "Mauritânia", continent: "África", capital: "Nouakchott", code: "MR" },
    { name: "Moçambique", continent: "África", capital: "Maputo", code: "MZ" },
    { name: "Namíbia", continent: "África", capital: "Windhoek", code: "NA" },
    { name: "Níger", continent: "África", capital: "Niamey", code: "NE" },
    { name: "Nigéria", continent: "África", capital: "Abuja", code: "NG" },
    { name: "Quênia", continent: "África", capital: "Nairóbi", code: "KE" },
    { name: "República Centro-Africana", continent: "África", capital: "Bangui", code: "CF" },
    { name: "República Democrática do Congo", continent: "África", capital: "Kinshasa", code: "CD" },
    { name: "Ruanda", continent: "África", capital: "Kigali", code: "RW" },
    { name: "São Tomé e Príncipe", continent: "África", capital: "São Tomé", code: "ST" },
    { name: "Senegal", continent: "África", capital: "Dacar", code: "SN" },
    { name: "Serra Leoa", continent: "África", capital: "Freetown", code: "SL" },
    { name: "Seychelles", continent: "África", capital: "Victoria", code: "SC" },
    { name: "Somália", continent: "África", capital: "Mogadíscio", code: "SO" },
    { name: "Sudão", continent: "África", capital: "Cartum", code: "SD" },
    { name: "Sudão do Sul", continent: "África", capital: "Juba", code: "SS" },
    { name: "Tanzânia", continent: "África", capital: "Dodoma", code: "TZ" },
    { name: "Togo", continent: "África", capital: "Lomé", code: "TG" },
    { name: "Tunísia", continent: "África", capital: "Túnis", code: "TN" },
    { name: "Uganda", continent: "África", capital: "Kampala", code: "UG" },
    { name: "Zâmbia", continent: "África", capital: "Lusaka", code: "ZM" },
    { name: "Zimbábue", continent: "África", capital: "Harare", code: "ZW" },

    // Ásia (47 países)
    { name: "Afeganistão", continent: "Ásia", capital: "Cabul", code: "AF" },
    { name: "Arábia Saudita", continent: "Ásia", capital: "Riad", code: "SA" },
    { name: "Armênia", continent: "Ásia", capital: "Erevan", code: "AM" },
    { name: "Azerbaijão", continent: "Ásia", capital: "Baku", code: "AZ" },
    { name: "Bahrain", continent: "Ásia", capital: "Manama", code: "BH" },
    { name: "Bangladesh", continent: "Ásia", capital: "Daca", code: "BD" },
    { name: "Brunei", continent: "Ásia", capital: "Bandar Seri Begawan", code: "BN" },
    { name: "Butão", continent: "Ásia", capital: "Thimphu", code: "BT" },
    { name: "Camboja", continent: "Ásia", capital: "Phnom Penh", code: "KH" },
    { name: "Catar", continent: "Ásia", capital: "Doha", code: "QA" },
    { name: "Cazaquistão", continent: "Ásia", capital: "Astana", code: "KZ" },
    { name: "China", continent: "Ásia", capital: "Pequim", code: "CN" },
    { name: "Chipre", continent: "Ásia", capital: "Nicósia", code: "CY" },
    { name: "Cingapura", continent: "Ásia", capital: "Cingapura", code: "SG" },
    { name: "Coreia do Norte", continent: "Ásia", capital: "Pyongyang", code: "KP" },
    { name: "Coreia do Sul", continent: "Ásia", capital: "Seul", code: "KR" },
    { name: "Emirados Árabes Unidos", continent: "Ásia", capital: "Abu Dhabi", code: "AE" },
    { name: "Filipinas", continent: "Ásia", capital: "Manila", code: "PH" },
    { name: "Geórgia", continent: "Ásia", capital: "Tbilisi", code: "GE" },
    { name: "Iêmen", continent: "Ásia", capital: "Sanaa", code: "YE" },
    { name: "Índia", continent: "Ásia", capital: "Nova Delhi", code: "IN" },
    { name: "Indonésia", continent: "Ásia", capital: "Jacarta", code: "ID" },
    { name: "Irã", continent: "Ásia", capital: "Teerã", code: "IR" },
    { name: "Iraque", continent: "Ásia", capital: "Bagdá", code: "IQ" },
    { name: "Israel", continent: "Ásia", capital: "Jerusalém", code: "IL" },
    { name: "Japão", continent: "Ásia", capital: "Tóquio", code: "JP" },
    { name: "Jordânia", continent: "Ásia", capital: "Amã", code: "JO" },
    { name: "Kuwait", continent: "Ásia", capital: "Cidade do Kuwait", code: "KW" },
    { name: "Laos", continent: "Ásia", capital: "Vientiane", code: "LA" },
    { name: "Líbano", continent: "Ásia", capital: "Beirute", code: "LB" },
    { name: "Malásia", continent: "Ásia", capital: "Kuala Lumpur", code: "MY" },
    { name: "Maldivas", continent: "Ásia", capital: "Malé", code: "MV" },
    { name: "Mianmar", continent: "Ásia", capital: "Naypyidaw", code: "MM" },
    { name: "Mongólia", continent: "Ásia", capital: "Ulaanbaatar", code: "MN" },
    { name: "Nepal", continent: "Ásia", capital: "Katmandu", code: "NP" },
    { name: "Omã", continent: "Ásia", capital: "Mascate", code: "OM" },
    { name: "Paquistão", continent: "Ásia", capital: "Islamabad", code: "PK" },
    { name: "Quirguistão", continent: "Ásia", capital: "Bishkek", code: "KG" },
    { name: "Síria", continent: "Ásia", capital: "Damasco", code: "SY" },
    { name: "Sri Lanka", continent: "Ásia", capital: "Sri Jayawardenepura Kotte", code: "LK" },
    { name: "Tailândia", continent: "Ásia", capital: "Bangkok", code: "TH" },
    { name: "Tajiquistão", continent: "Ásia", capital: "Dushanbe", code: "TJ" },
    { name: "Timor-Leste", continent: "Ásia", capital: "Díli", code: "TL" },
    { name: "Turcomenistão", continent: "Ásia", capital: "Ashgabat", code: "TM" },
    { name: "Turquia", continent: "Ásia", capital: "Ancara", code: "TR" },
    { name: "Uzbequistão", continent: "Ásia", capital: "Tashkent", code: "UZ" },
    { name: "Vietnã", continent: "Ásia", capital: "Hanói", code: "VN" },

    // Europa (44 países)
    { name: "Albânia", continent: "Europa", capital: "Tirana", code: "AL" },
    { name: "Alemanha", continent: "Europa", capital: "Berlim", code: "DE" },
    { name: "Andorra", continent: "Europa", capital: "Andorra la Vella", code: "AD" },
    { name: "Áustria", continent: "Europa", capital: "Viena", code: "AT" },
    { name: "Bélgica", continent: "Europa", capital: "Bruxelas", code: "BE" },
    { name: "Bielorrússia", continent: "Europa", capital: "Minsk", code: "BY" },
    { name: "Bósnia e Herzegovina", continent: "Europa", capital: "Sarajevo", code: "BA" },
    { name: "Bulgária", continent: "Europa", capital: "Sófia", code: "BG" },
    { name: "Croácia", continent: "Europa", capital: "Zagreb", code: "HR" },
    { name: "Dinamarca", continent: "Europa", capital: "Copenhague", code: "DK" },
    { name: "Eslováquia", continent: "Europa", capital: "Bratislava", code: "SK" },
    { name: "Eslovênia", continent: "Europa", capital: "Liubliana", code: "SI" },
    { name: "Espanha", continent: "Europa", capital: "Madri", code: "ES" },
    { name: "Estônia", continent: "Europa", capital: "Tallinn", code: "EE" },
    { name: "Finlândia", continent: "Europa", capital: "Helsinque", code: "FI" },
    { name: "França", continent: "Europa", capital: "Paris", code: "FR" },
    { name: "Grécia", continent: "Europa", capital: "Atenas", code: "GR" },
    { name: "Hungria", continent: "Europa", capital: "Budapeste", code: "HU" },
    { name: "Irlanda", continent: "Europa", capital: "Dublin", code: "IE" },
    { name: "Islândia", continent: "Europa", capital: "Reiquiavique", code: "IS" },
    { name: "Itália", continent: "Europa", capital: "Roma", code: "IT" },
    { name: "Letônia", continent: "Europa", capital: "Riga", code: "LV" },
    { name: "Liechtenstein", continent: "Europa", capital: "Vaduz", code: "LI" },
    { name: "Lituânia", continent: "Europa", capital: "Vilnius", code: "LT" },
    { name: "Luxemburgo", continent: "Europa", capital: "Luxemburgo", code: "LU" },
    { name: "Macedônia do Norte", continent: "Europa", capital: "Skopje", code: "MK" },
    { name: "Malta", continent: "Europa", capital: "Valeta", code: "MT" },
    { name: "Moldávia", continent: "Europa", capital: "Chișinău", code: "MD" },
    { name: "Mônaco", continent: "Europa", capital: "Mônaco", code: "MC" },
    { name: "Montenegro", continent: "Europa", capital: "Podgorica", code: "ME" },
    { name: "Noruega", continent: "Europa", capital: "Oslo", code: "NO" },
    { name: "Países Baixos", continent: "Europa", capital: "Amsterdã", code: "NL" },
    { name: "Polônia", continent: "Europa", capital: "Varsóvia", code: "PL" },
    { name: "Portugal", continent: "Europa", capital: "Lisboa", code: "PT" },
    { name: "Reino Unido", continent: "Europa", capital: "Londres", code: "GB" },
    { name: "República Tcheca", continent: "Europa", capital: "Praga", code: "CZ" },
    { name: "Romênia", continent: "Europa", capital: "Bucareste", code: "RO" },
    { name: "Rússia", continent: "Europa", capital: "Moscou", code: "RU" },
    { name: "San Marino", continent: "Europa", capital: "San Marino", code: "SM" },
    { name: "Sérvia", continent: "Europa", capital: "Belgrado", code: "RS" },
    { name: "Suécia", continent: "Europa", capital: "Estocolmo", code: "SE" },
    { name: "Suíça", continent: "Europa", capital: "Berna", code: "CH" },
    { name: "Ucrânia", continent: "Europa", capital: "Kiev", code: "UA" },
    { name: "Vaticano", continent: "Europa", capital: "Vaticano", code: "VA" },

    // América do Norte (23 países)
    { name: "Antígua e Barbuda", continent: "América do Norte", capital: "Saint John's", code: "AG" },
    { name: "Bahamas", continent: "América do Norte", capital: "Nassau", code: "BS" },
    { name: "Barbados", continent: "América do Norte", capital: "Bridgetown", code: "BB" },
    { name: "Belize", continent: "América do Norte", capital: "Belmopan", code: "BZ" },
    { name: "Canadá", continent: "América do Norte", capital: "Ottawa", code: "CA" },
    { name: "Costa Rica", continent: "América do Norte", capital: "San José", code: "CR" },
    { name: "Cuba", continent: "América do Norte", capital: "Havana", code: "CU" },
    { name: "Dominica", continent: "América do Norte", capital: "Roseau", code: "DM" },
    { name: "El Salvador", continent: "América do Norte", capital: "San Salvador", code: "SV" },
    { name: "Estados Unidos", continent: "América do Norte", capital: "Washington, D.C.", code: "US" },
    { name: "Granada", continent: "América do Norte", capital: "Saint George's", code: "GD" },
    { name: "Guatemala", continent: "América do Norte", capital: "Cidade da Guatemala", code: "GT" },
    { name: "Haiti", continent: "América do Norte", capital: "Porto Príncipe", code: "HT" },
    { name: "Honduras", continent: "América do Norte", capital: "Tegucigalpa", code: "HN" },
    { name: "Jamaica", continent: "América do Norte", capital: "Kingston", code: "JM" },
    { name: "México", continent: "América do Norte", capital: "Cidade do México", code: "MX" },
    { name: "Nicarágua", continent: "América do Norte", capital: "Manágua", code: "NI" },
    { name: "Panamá", continent: "América do Norte", capital: "Cidade do Panamá", code: "PA" },
    { name: "República Dominicana", continent: "América do Norte", capital: "Santo Domingo", code: "DO" },
    { name: "Santa Lúcia", continent: "América do Norte", capital: "Castries", code: "LC" },
    { name: "São Cristóvão e Nevis", continent: "América do Norte", capital: "Basseterre", code: "KN" },
    { name: "São Vicente e Granadinas", continent: "América do Norte", capital: "Kingstown", code: "VC" },
    { name: "Trinidad e Tobago", continent: "América do Norte", capital: "Port of Spain", code: "TT" },

    // América do Sul (12 países)
    { name: "Argentina", continent: "América do Sul", capital: "Buenos Aires", code: "AR" },
    { name: "Bolívia", continent: "América do Sul", capital: "La Paz", code: "BO" },
    { name: "Brasil", continent: "América do Sul", capital: "Brasília", code: "BR" },
    { name: "Chile", continent: "América do Sul", capital: "Santiago", code: "CL" },
    { name: "Colômbia", continent: "América do Sul", capital: "Bogotá", code: "CO" },
    { name: "Equador", continent: "América do Sul", capital: "Quito", code: "EC" },
    { name: "Guiana", continent: "América do Sul", capital: "Georgetown", code: "GY" },
    { name: "Paraguai", continent: "América do Sul", capital: "Assunção", code: "PY" },
    { name: "Peru", continent: "América do Sul", capital: "Lima", code: "PE" },
    { name: "Suriname", continent: "América do Sul", capital: "Paramaribo", code: "SR" },
    { name: "Uruguai", continent: "América do Sul", capital: "Montevidéu", code: "UY" },
    { name: "Venezuela", continent: "América do Sul", capital: "Caracas", code: "VE" },

    // Oceania (14 países)
    { name: "Austrália", continent: "Oceania", capital: "Camberra", code: "AU" },
    { name: "Fiji", continent: "Oceania", capital: "Suva", code: "FJ" },
    { name: "Ilhas Marshall", continent: "Oceania", capital: "Majuro", code: "MH" },
    { name: "Ilhas Salomão", continent: "Oceania", capital: "Honiara", code: "SB" },
    { name: "Kiribati", continent: "Oceania", capital: "Tarawa", code: "KI" },
    { name: "Micronésia", continent: "Oceania", capital: "Palikir", code: "FM" },
    { name: "Nauru", continent: "Oceania", capital: "Yaren", code: "NR" },
    { name: "Nova Zelândia", continent: "Oceania", capital: "Wellington", code: "NZ" },
    { name: "Palau", continent: "Oceania", capital: "Ngerulmud", code: "PW" },
    { name: "Papua Nova Guiné", continent: "Oceania", capital: "Port Moresby", code: "PG" },
    { name: "Samoa", continent: "Oceania", capital: "Apia", code: "WS" },
    { name: "Tonga", continent: "Oceania", capital: "Nuku'alofa", code: "TO" },
    { name: "Tuvalu", continent: "Oceania", capital: "Funafuti", code: "TV" },
    { name: "Vanuatu", continent: "Oceania", capital: "Port Vila", code: "VU" }
];